
GET http://localhost:3000/get  

###

POST http://localhost:3000/?title=ayyachi&year=2020&rating=7

###

PATCH http://localhost:3000/edit/63b073a30d2f2247d03036cf?title=hola&year=2000

###
DELETE http://localhost:3000/delete/63b0acf2b548a1df3e6acd2a

###
GET http://localhost:3000/moviesDB/get

###
POST http://localhost:3000/register?email=1@2.com&password=123
###
GET http://localhost:3000/moviesDB/63aef70e99f45fd3f0633c06

###
POST http://localhost:3000/login?email=1@2.com&password=123

###

DELETE http://localhost:3000/delete/?email=1@2.com&password=222

###
PATCH http://localhost:3000/edit?email=1@2.com&password=222

###
GET http://localhost:3000/tesst